# 마크다운

## 마크다운

### 마크다운

markdown explanation search for it, font size control with #

##### 변수선언

In [ ]:
a = 1; print(a)
a

In [ ]:
a = 1; a = float(a); print(type(a))

In [1]:
a = 1.0
a

1.0

In [2]:
type(a)

float

In [3]:
a = "c"
type(a)

str

In [ ]:
a = 1.1
int(float(int(a)))

In [4]:
a = '123'

In [5]:
type(a)

str

In [6]:
a[1]

'2'

In [7]:
a(1)

TypeError: 'str' object is not callable

In [8]:
a{1}

SyntaxError: invalid syntax (<ipython-input-8-232b3f6e9a88>, line 1)

In [9]:
a='1bat'
a{1}

SyntaxError: invalid syntax (<ipython-input-9-893eb62a7268>, line 2)

In [10]:
a[1]

'2'

In [11]:
a='1bat'
a[1]

'b'

In [12]:
a[0]

'1'

In [13]:
a[-1]

't'

In [14]:
a[-2]

'a'

In [15]:
a = [1,2,3]

In [16]:
a

[1, 2, 3]

In [17]:
b = {1,2,3}

In [18]:
a, b

([1, 2, 3], {1, 2, 3})

In [19]:
a
b

{1, 2, 3}

In [20]:
print(a) print(b)

SyntaxError: invalid syntax (<ipython-input-20-a01319e25c28>, line 1)

In [21]:
print(a); print(b)

[1, 2, 3]
{1, 2, 3}


In [22]:
type(a)

list

In [23]:
type(b)

set

In [24]:
a[-1]

3

In [25]:
b[-1]

TypeError: 'set' object does not support indexing

In [26]:
b{-1}

SyntaxError: invalid syntax (<ipython-input-26-8f48b0e9d98a>, line 1)

In [27]:
b(-1)

TypeError: 'set' object is not callable

In [32]:
c = [1, 2, 'ab', [4,5]]

In [33]:
c[-1][0]

4

In [34]:
e='123'; e=list(e);

In [35]:
e

['1', '2', '3']

In [2]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [3]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

{'a': 'apple', 'b': 'orange', 'c': 2014}
<class 'numpy.ndarray'>


In [4]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [5]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [6]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [7]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [8]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [9]:
c*c.T

matrix([[14, 19],
        [19, 73]])